### PR TITLE
Doc

### PR DESCRIPTION
**Pull request by brandimarte**
Finished transferring data from Thomas wiki. I left-out some information on purpose, but verification is required.

We now have a skeleton, so everyone can start to document the classes/objects/functions that it will "appear" at the reference documentation.

A bunch of warnings are still generated when building with sphinx, most of then complaining about indentation. I think we can fix then together with the documentation process.

### CODE REVIEW

**Comment by zerothi** [comment]
In regards of this, you may use the `pep8.sh` script in sisl to fix alot of PEP8 related indentation issues.

This should in principle also handle some of the things in documentation, I think.
I.e. once this PR is merged, I would suggest to do that. :)

**Comment by zerothi** [comment]
Or maybe you could do it in this PR, which would do everything in one go :)

**Comment by tfrederiksen** [comment]
Looks good. Pedro, please decide and merge.

**Comment by brandimarte** [comment]
Cool! Let me try to follow Nick's suggestion first before merging!

**Pull request merged**
