### PR TITLE
Tutorial for upcoming CECAM school

### PR DESCRIPTION
**Pull request by tfrederiksen**
This branch is intended to develop interactive tutorial material based on jupyter-notebooks and [sisl](https://github.com/zerothi/sisl/) for the upcoming CECAM event [Advanced school on Quantum Transport using SIESTA](https://www.cecam.org/workshop-details/4/):

* `IN_01`: a CO molecule between 1D Cu electrodes

### CODE REVIEW

**Comment by zerothi** [comment]
just a small comment. I generally advice against using binary files. In this case it probably doesn't matter much. But version controlling binary files is a bit of a mess since each change to a file requires the full file to be stored (rather than small patches).
I would change vps to psf file format, if able.

**Comment by tfrederiksen** [comment]
Thanks for your remarks, @zerothi . I agree this is not optimal, but the binary pseudos are the same ones as used in the `Examples/STMimage` folder. I am reluctant to try to build the corresponding psf files now from scratch.

**Comment by zerothi** [comment]
> Thanks for your remarks, @zerothi . I agree this is not optimal, but the binary pseudos are the same ones as used in the `Examples/STMimage` folder. I am reluctant to try to build the corresponding psf files now from scratch.

Ok, you could use the `vpsb2asc` utility shipped with atom, it translates a vps file to psf file format. No need to get original input files or anything.

**Comment by tfrederiksen** [comment]
> > Thanks for your remarks, @zerothi . I agree this is not optimal, but the binary pseudos are the same ones as used in the `Examples/STMimage` folder. I am reluctant to try to build the corresponding psf files now from scratch.
> 
> Ok, you could use the `vpsb2asc` utility shipped with atom, it translates a vps file to psf file format. No need to get original input files or anything.

Nice. Didn't know about this utility!

**Pull request merged**
